-- Ensure clicks table exists and has necessary columns
CREATE TABLE IF NOT EXISTS public.clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id BIGINT REFERENCES public.links(id),
    slug TEXT,
    country TEXT,
    city TEXT,
    ip_address TEXT,
    user_agent TEXT,
    referer TEXT,
    os TEXT,
    device TEXT,
    browser TEXT,
    click_id TEXT, -- For tracking unique clicks from ad networks
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_clicks_link_id ON public.clicks(link_id);
CREATE INDEX IF NOT EXISTS idx_clicks_slug ON public.clicks(slug);
CREATE INDEX IF NOT EXISTS idx_clicks_created_at ON public.clicks(created_at);
